### ISSUE TITLE
Importing doesn't work

### ISSUE THREAD

**Issue by TheAlex626** [mohsenph69/Godot-MTerrain-plugin#14]
Hi! I am using Godot [4.1.3.stable.official] and I'm trying to import the heightmap. I do like the documentation/video says, I import my heightmap file, set the dimensions and min/max height, create a data folder for it. But when I press "Import", nothing happens.

**Comment by mohsenph69** [comment]
What height-map format do you use?
Does that give you any error?
send me a photo of parameter in import window if you can
