### ISSUE TITLE
Defining custom vertex data for the map

### ISSUE THREAD

**Issue by michalusio** [mohsenph69/Godot-MTerrain-plugin#15]
Hi!

First of all - great plugin!

Is it possible to define custom vertex data (CUSTOM0-3) to be passed in along with the heightmap data?

Thanks in advance for the answer.

**Comment by mohsenph69** [comment]
This Terrain plugin reuse the Mesh Chunk in generated terrain. That means one terrain mesh chunk could be copied and places in multiple place.
Custom Vertex data need a unique mesh which will not work with this system
The best is to pass an terrain image to shader  and sample that in vertex shader, which is also very efficient
