### ISSUE TITLE
Saving causes massive freeze in editor

### ISSUE THREAD

**Issue by nickpolet** [mohsenph69/Godot-MTerrain-plugin#16]
Once the terrain has been created in the editor, saving the scene causes a long freeze in the editor. This is more noticeable with larger terrain. Can add quite a lot of time when working on a scene with large terrain.

Would there be an option to not save anything when the scene is saved, or anything to help speed up the save process?

I'm not sure what part is slow when saving the scene... interested to hear if you've got any ideas?

**Comment by nickpolet** [comment]
After a bit of digging, I found that `grid->save_all_dirty_images();` in mterrain.cpp is the culprit. Obviously this is required for most use cases, as you want changes that are painted onto the terrain to be saved.

My current use case, is heightmaps and splatmaps coming from WorldMachine. So saving the dirty images on every save doesn't make sense for me, and is slowing me down quite a bit.

Could I add a suggestion to make a boolean on the mterrain node, that disables dirty image saving when the scene is saved?

**Comment by mohsenph69** [comment]
> Could I add a suggestion to make a boolean on the mterrain node, that disables dirty image saving when the scene is saved?

Yeah That is a good Idea, We can add a boolean!
I think the better way is to put everything in  a separate CPU thread so nothing will be freeze, But for now boolean is more simple
But the saving system only save those images which has been changed (Not all images), If you don't change anything (Sculpt or paint) it will save nothing, It should not freeze too long, maybe I will check that later if it has some bug or something

**Comment by mohsenph69** [comment]
There was a bug inside **MImage.cpp**  `save method` in the new update I solve that!

Test terrain, if you don't change any thing on terrain I mean no sculpt and not paint, noting should save, and there will be no freeze!

Hopefully that will work

If it work we can close this!

**Comment by nickpolet** [comment]
Just tested the latest release, and it works perfectly when saving the scene without any changes to the terrain. For me this is a HUGE update to mterrain. 

Also noticed that loading the terrain is much quicker now. Takes it from around 30 seconds to load a 16km x 16km terrain down to a couple of seconds. Really massive improvement.

Thanks for that, will close this out now.

**Comment by mohsenph69** [comment]
That is good

Basically this time Terrain will load only those region which should be shown! and will load the rest of them when needed in run-time.
