### ISSUE TITLE
Import with error

### ISSUE THREAD

**Issue by loongEgg** [mohsenph69/Godot-MTerrain-plugin#19]
the message is:
Error loading extension:res//Godot-MTerrain-plugin-0.9.3/libs/MTerrain.gdextension

my godot vesion is: v4.0.2
![image](https://github.com/mohsenph69/Godot-MTerrain-plugin/assets/41780693/8b7cf2ac-bc30-47d0-a592-3667d6185692)

**Comment by mohsenph69** [comment]
The GDExtension library has been build for Godot 4.1, and if you look the **MTerrain.gdextension** file it's said minimum version required is 4.1

I think this will work with Godot 4.2, But if you want to run this on Godot 4.0, You need to change the Godot-Cpp version in GDExtension folder to 4.0, and remove minimum version required in **MTerrain.gdextension** file, and build the library by yourself, That may work and may not work, I am not sure
