### ISSUE TITLE
Create auto disable (problem)

### ISSUE THREAD

**Issue by agung098** [mohsenph69/Godot-MTerrain-plugin#21]
Create button disable if run scene or out of scene

**Comment by mohsenph69** [comment]
Can you explain more in detail, about what should be disabled! and how exactly it should work?

Thanks

**Comment by agung098** [comment]
I'm not sure if this is my mistake or not, but when I run the game, the terrain doesn't form, and every time I switch scenes, the terrain disappears or creates a disabled button.

**Comment by mohsenph69** [comment]
Terrain Does not create automatically
You should call `create_grid()` in ready function

**Comment by agung098** [comment]
Sorry but ican't found where is that ready function

**Comment by ArtyIF** [comment]
> Terrain Does not create automatically You should call `create_grid()` in ready function

I believe this should be made clear in the guide. Haven't watched the video guide much, it goes into the under-the-hood details too much, but I haven't seen anything in the text guide that mentions that I should create a script that does this.

**Comment by agung098** [comment]
I think this big problem for new user

**Comment by mohsenph69** [comment]
> > Terrain Does not create automatically You should call `create_grid()` in ready function
> 
> I believe this should be made clear in the guide. Haven't watched the video guide much, it goes into the under-the-hood details too much, but I haven't seen anything in the text guide that mentions that I should create a script that does this.

You are right man, People can confuse about this, I add a note in the main wiki page!
