### ISSUE TITLE
Error: version `GLIBC_2.38' not found

### ISSUE THREAD

**Issue by nickpolet** [mohsenph69/Godot-MTerrain-plugin#6]
Trying to install through the AssetLib tab in Godot 4.1.1(official), using Ubuntu 22.04.

The files download fine, but the error below appears when trying to enable the plugin.

![image](https://github.com/mohsenph69/Godot-MTerrain-plugin/assets/5023909/8fc63d65-80fd-4ffd-9d64-a81b2f21afa2)

---

This seems to be something to do with glibc, but I'm not sure exactly what the issue is here. Any ideas?

**Comment by mohsenph69** [comment]
I think the GDExtension lib want glibc with higher version, it seems the minimum accepted version of glibc is **2.38**

Look what is your version?

Try to update your Linux maybe that will fix that, OR you can build the GDExtension lib that by yourself and see if that will work

**Comment by prfiredragon** [comment]
Same issue. I build it from source.

**Comment by nickpolet** [comment]
Yep, I built from source and it works well.

Thanks all.
