### ISSUE TITLE
godot-cpp has unexposed UtilityFunctions::is_instance_valid():

### ISSUE THREAD

**Issue by zhwei820** [mohsenph69/Godot-MTerrain-plugin#60]
crash when build in mac.

  Can't open dynamic library: /Users/zhouw/Desktop/projects/tpc/addons/m_terrain/libs/libMTerrain.macos.template_debug.universal.dylib. Error: dlopen(/Users/zhouw/Desktop/projects/tpc/addons/m_terrain/libs/libMTerrain.macos.template_debug.universal.dylib, 0x0002): symbol not found in flat namespace '__ZN5godot16UtilityFunctions17is_instance_validERKNS_7VariantE'.

godot-cpp has Unexpose UtilityFunctions::is_instance_valid():

<img width="622" alt="image" src="https://github.com/user-attachments/assets/328299b3-7fd7-4de8-9bcb-fe13510c52ce">

https://github.com/godotengine/godot-cpp/releases/tag/godot-4.3-stable

**Comment by mohsenph69** [comment]
This is happen in Godot4.3! as they removed this function!

Try to clone the latest terrain repo another time it won't happen
